### PR TITLE
Create ChatHeader with HTML/CSS issue #261

### PR DESCRIPTION
**Pull request by Seundede**
Created ChatHeader with HTML/CSS issue #261

### CODE REVIEW

**Review by Sherlock-HolmesJM — APPROVED** [review]
....

**Review by Sherlock-HolmesJM — COMMENTED** [review]
....

**Review by Sherlock-HolmesJM — COMMENTED** [review]
I can see your code looks okay. However, your branch has conflicts with the zurichat dev branch.

Do a git pull upstream dev to have your local branch updated

**Comment by Seundede** [comment]
Created ChatHeader with HTML/CSS issue #261

**Pull request closed without merging**
